vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        dish_image:
            uri_prefix: '%app.path.dishes_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.dishes_images%'
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
            namer:
                service: Vich\UploaderBundle\Naming\PropertyNamer
                options: { property: 'slug' }
